#!/bin/bash
# tensorboard --logdir . --port 8888 --bind_all

# treina os modelos no espaço original, não no espaço latente do VAE e faz a comparação entre eles
app/eval_vae_classifier rave 1d
app/eval_vae_classifier rave 2d

# treina modelos para classificar: dado original vs dado reconstruído pelo VAE
python app/iemanja_vs_vae_classifier.py --dataset1-dir /data/iemanja_truncated/ --dataset2-dir /data/iemanja_vae/rave --ie-representation raw --model cnn1d --output-dir ./result/vae_classifiers/original_vs_reconstructed/rave/time
python app/iemanja_vs_vae_classifier.py --dataset1-dir /data/iemanja_truncated/ --dataset2-dir /data/iemanja_vae/rave --ie-representation spectral --model cnn2d --output-dir ./result/vae_classifiers/original_vs_reconstructed/rave/spectral

# treina modelos para classificar os dados originais no espaço latente do VAE
python app/iemanja_classifier.py --ie-target CLASS --ie-representation latent --model mlp --output-dir ./result/vae_classifiers/trained_models/latent/rave/ship --ie-dataset-dir /data/iemanja_truncated --ie-latent-model /data/models/rave.ts
python app/iemanja_classifier.py --model mlp --ie-target "NAME_(US)" --ie-representation latent --output-dir ./result/vae_classifiers/trained_models/latent/rave/channel --ie-dataset-dir /data/iemanja_truncated --ie-latent-model /data/models/rave.ts




# python test/test_svdd.py --ie-representation spectral --ie-cnn-flatten --ie-dataset-dir /data/iemanja_truncated/ --output-dir ./result/svdd/models/mel

# python test/test_svdd.py --ie-representation spectral --ie-cnn-models ./result/vae_classifiers/ship/original/ --ie-cnn-flatten --ie-dataset-dir /data/iemanja_truncated/ --output-dir ./result/svdd/models/ship

# python test/test_svdd.py --ie-representation spectral --ie-cnn-models ./result/vae_classifiers/channel/original/ --ie-cnn-flatten --ie-dataset-dir /data/iemanja_truncated/ --output-dir ./result/svdd/models/channel

# python test/test_svdd.py --ie-representation spectral --ie-cnn-models ./result/vae_classifiers/ship/original/ ./result/vae_classifiers/channel/original/ --ie-cnn-flatten --ie-dataset-dir /data/iemanja_truncated/ --output-dir ./result/svdd/models/combined

# python test/test_svdd.py --ie-representation raw --ie-dataset-dir /data/iemanja_truncated/ --output-dir ./result/svdd/models/time

# python test/test_svdd.py --ie-representation spectral --ie-cnn-flatten --ie-dataset-dir /data/iemanja_truncated/ --output-dir ./result/svdd/models/mel



# python test/test_svdd_metrics.py --svdd-model ./result/svdd/models/ship/ --dataset1-dir /data/iemanja_truncated/ --dataset2-dir /data/iemanja_vae/rave/ --ie-representation spectral --ie-cnn-models ./result/vae_classifiers/ship/original/ --ie-cnn-flatten --output-dir ./result/svdd/metrics/ship-rave

# python test/test_svdd_metrics.py --svdd-model ./result/svdd/models/channel/ --dataset1-dir /data/iemanja_truncated/ --dataset2-dir /data/iemanja_vae/rave/ --ie-representation spectral --ie-cnn-models ./result/vae_classifiers/channel/original/ --ie-cnn-flatten --output-dir ./result/svdd/metrics/channel-rave

# python test/test_svdd_metrics.py --svdd-model ./result/svdd/models/combined/ --dataset1-dir /data/iemanja_truncated/ --dataset2-dir /data/iemanja_vae/rave/ --ie-representation spectral --ie-cnn-models ./result/vae_classifiers/ship/original/ ./result/vae_classifiers/channel/original/ --ie-cnn-flatten --output-dir ./result/svdd/metrics/combined-rave

# python test/test_svdd_metrics.py --svdd-model ./result/svdd/models/time/ --dataset1-dir /data/iemanja_truncated/ --dataset2-dir /data/iemanja_vae/rave/ --ie-representation raw --output-dir ./result/svdd/metrics/time-rave

# python test/test_svdd_metrics.py --svdd-model ./result/svdd/models/mel/ --dataset1-dir /data/iemanja_truncated/ --dataset2-dir /data/iemanja_vae/rave/ --ie-representation spectral --output-dir ./result/svdd/metrics/mel-rave


################ Evaluate model steps during VAE training

# python test/eval_vae_loss_over_training.py --model-dir /data/models/vae_steps/ --output-dir ./result/training_steps_vae_evaluation/vae_latent_classification

# python test/eval_vae_classification_over_training.py --model-dir /data/models/vae_steps/ --output-dir ./result/training_steps_vae_evaluation/vae_latent_classification/ship

# python test/eval_vae_classification_over_training.py --ie-target "NAME_(US)" --model-dir /data/models/vae_steps/ --output-dir ./result/training_steps_vae_evaluation/vae_latent_classification/channel