#!/bin/bash
# tensorboard --logdir . --port 8888 --bind_all


# python test/test_svdd.py --ie-representation spectral --ie-cnn-flatten --ie-dataset-dir /data/iemanja_truncated/ --output-dir ./result/svdd/models/mel

# python test/test_svdd.py --ie-representation spectral --ie-cnn-models ./result/vae_classifiers/ship/original/ --ie-cnn-flatten --ie-dataset-dir /data/iemanja_truncated/ --output-dir ./result/svdd/models/ship

# python test/test_svdd.py --ie-representation spectral --ie-cnn-models ./result/vae_classifiers/channel/original/ --ie-cnn-flatten --ie-dataset-dir /data/iemanja_truncated/ --output-dir ./result/svdd/models/channel

# python test/test_svdd.py --ie-representation spectral --ie-cnn-models ./result/vae_classifiers/ship/original/ ./result/vae_classifiers/channel/original/ --ie-cnn-flatten --ie-dataset-dir /data/iemanja_truncated/ --output-dir ./result/svdd/models/combined

# python test/test_svdd.py --ie-representation raw --ie-dataset-dir /data/iemanja_truncated/ --output-dir ./result/svdd/models/time

# python test/test_svdd.py --ie-representation spectral --ie-cnn-flatten --ie-dataset-dir /data/iemanja_truncated/ --output-dir ./result/svdd/models/mel



# python test/test_svdd_metrics.py --svdd-model ./result/svdd/models/ship/ --dataset1-dir /data/iemanja_truncated/ --dataset2-dir /data/iemanja_vae/rave/ --ie-representation spectral --ie-cnn-models ./result/vae_classifiers/ship/original/ --ie-cnn-flatten --output-dir ./result/svdd/metrics/ship-rave

# python test/test_svdd_metrics.py --svdd-model ./result/svdd/models/channel/ --dataset1-dir /data/iemanja_truncated/ --dataset2-dir /data/iemanja_vae/rave/ --ie-representation spectral --ie-cnn-models ./result/vae_classifiers/channel/original/ --ie-cnn-flatten --output-dir ./result/svdd/metrics/channel-rave

# python test/test_svdd_metrics.py --svdd-model ./result/svdd/models/combined/ --dataset1-dir /data/iemanja_truncated/ --dataset2-dir /data/iemanja_vae/rave/ --ie-representation spectral --ie-cnn-models ./result/vae_classifiers/ship/original/ ./result/vae_classifiers/channel/original/ --ie-cnn-flatten --output-dir ./result/svdd/metrics/combined-rave

# python test/test_svdd_metrics.py --svdd-model ./result/svdd/models/time/ --dataset1-dir /data/iemanja_truncated/ --dataset2-dir /data/iemanja_vae/rave/ --ie-representation raw --output-dir ./result/svdd/metrics/time-rave

# python test/test_svdd_metrics.py --svdd-model ./result/svdd/models/mel/ --dataset1-dir /data/iemanja_truncated/ --dataset2-dir /data/iemanja_vae/rave/ --ie-representation spectral --output-dir ./result/svdd/metrics/mel-rave


################ Evaluate model steps during VAE training

python test/eval_vae_loss_over_training.py --model-dir /data/models/vae_steps/ --output-dir ./result/training_steps_vae_evaluation/vae_latent_classification

python test/eval_vae_classification_over_training.py --model-dir /data/models/vae_steps/ --output-dir ./result/training_steps_vae_evaluation/vae_latent_classification/ship

python test/eval_vae_classification_over_training.py --ie-target "NAME_(US)" --model-dir /data/models/vae_steps/ --output-dir ./result/training_steps_vae_evaluation/vae_latent_classification/channel